name: "Write File (fork)"
author: "Sébastien Légaré"
description: "Write a file (forked from https://github.com/DamianReeves/write-file-action)"
inputs:
  path: # id of input
    description: "The path to the file to write"
    required: true

  contents:
    description: "The contents of the file"
    required: true

  write-mode:
    description: "The mode of writing to use: `overwrite`, `append`, or `preserve`."
    required: false
    default: preserve
    
  empty-line-eof:
    description: "Outputs an empty line at the end of the written file"
    required: false
    default: preserve
outputs:
  size:
    description: "The returned size"

runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "package"
  color: "gray-dark"
